"""update_schema_for_roles_and_orgs

Revision ID: 1f9aeb30a76e
Revises: c19456662756
Create Date: 2026-09-25 15:13:13.816946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9aeb30a76e'
down_revision: Union[str, Sequence[str], None] = 'c19456662756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_membership_user_org')
    )
    op.drop_table('memberships')
    op.add_column('organizations', sa.Column('website', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
    # Re-apply RLS for organization_memberships
    op.execute("ALTER TABLE organization_memberships ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE organization_memberships FORCE ROW LEVEL SECURITY;")
    op.execute("GRANT ALL ON organization_memberships TO authenticated;")
    
    op.execute("""
        CREATE POLICY "Tenant isolation for organization_memberships" ON organization_memberships
        FOR ALL
        USING (
            organization_id = NULLIF(current_setting('app.current_tenant', TRUE), '')::uuid
        );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("REVOKE ALL ON organization_memberships FROM authenticated;")
    op.execute("ALTER TABLE organization_memberships NO FORCE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS \"Tenant isolation for organization_memberships\" ON organization_memberships;")
    op.execute("ALTER TABLE organization_memberships DISABLE ROW LEVEL SECURITY;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'website')
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('memberships_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('memberships_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('memberships_pkey')),
    sa.UniqueConstraint('user_id', 'organization_id', name=op.f('uq_user_organization'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('organization_memberships')
    # ### end Alembic commands ###
