"""remove_must_change_password

Revision ID: d14c83010b29
Revises: 571dcf635d98
Create Date: 2026-09-27 16:54:47.003040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14c83010b29'
down_revision: Union[str, Sequence[str], None] = '571dcf635d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'must_change_password')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
