"""add_chat_tables

Revision ID: ee380cca564d
Revises: 59d0e41865ec
Create Date: 2026-10-04 15:39:21.334224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee380cca564d'
down_revision: Union[str, Sequence[str], None] = '59d0e41865ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_auth_user_id'), 'conversations', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_citations_message_id'), 'citations', ['message_id'], unique=False)
    
    # RLS Policies for new chat tables
    op.execute("ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE messages ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE citations ENABLE ROW LEVEL SECURITY;")
    
    op.execute("""
        CREATE POLICY "Tenant isolation for conversations" ON conversations
        FOR ALL USING (
            organization_id = (NULLIF(current_setting('app.current_tenant', true), ''))::uuid
        );
    """)
    
    op.execute("""
        CREATE POLICY "Tenant isolation for messages" ON messages
        FOR ALL USING (
            EXISTS (
                SELECT 1 FROM conversations c
                WHERE c.id = messages.conversation_id
                AND c.organization_id = (NULLIF(current_setting('app.current_tenant', true), ''))::uuid
            )
        );
    """)
    
    op.execute("""
        CREATE POLICY "Tenant isolation for citations" ON citations
        FOR ALL USING (
            EXISTS (
                SELECT 1 FROM messages m
                JOIN conversations c ON c.id = m.conversation_id
                WHERE m.id = citations.message_id
                AND c.organization_id = (NULLIF(current_setting('app.current_tenant', true), ''))::uuid
            )
        );
    """)
    
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON conversations, messages, citations TO authenticated;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON conversations, messages, citations FROM authenticated;")
    op.execute("DROP POLICY IF EXISTS \"Tenant isolation for citations\" ON citations;")
    op.execute("DROP POLICY IF EXISTS \"Tenant isolation for messages\" ON messages;")
    op.execute("DROP POLICY IF EXISTS \"Tenant isolation for conversations\" ON conversations;")
    op.execute("ALTER TABLE citations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE messages DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;")
    
    op.drop_index(op.f('ix_citations_message_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_auth_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
